"""empty message

Revision ID: 124cf2640268
Revises: bf6426174f42
Create Date: 2022-07-22 13:44:38.573703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124cf2640268'
down_revision = 'bf6426174f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
