"""empty message

Revision ID: a17380231a74
Revises: 0c036fc4034c
Create Date: 2022-08-01 12:22:23.653253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17380231a74'
down_revision = '0c036fc4034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_note', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'users', ['user_note'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'user_note')
    # ### end Alembic commands ###
