"""empty message

Revision ID: c03aea06fe21
Revises: 96033bbd21ec
Create Date: 2022-08-01 12:23:57.176704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03aea06fe21'
down_revision = '96033bbd21ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'content')
    # ### end Alembic commands ###
